allow_remote_control yes
listen_on unix:/tmp/kitty

shell_integration no-sudo
shell_integration no-title

include ~/.config/kitty/themes/synthwave84.conf

term xterm-kitty

font_size 15
font_family JetBrainsMono Nerd Font Mono

scrollback_lines 10000

shell zsh --login
editor nvim

hide_window_decorations titlebar-only
window_padding_width 1 5 2 2

confirm_os_window_close 0
enable_audio_bell no
macos_option_as_alt right

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_stop_blinking_after 0
cursor_trail 1
cursor_trail_decay 0.01 0.5
cursor_trail_start_threshold 0

background_opacity 0.85
background_blur 5
background_image ~/.config/kitty/backgrounds/synthwave84-bg.png
background_image_layout cscaled

tab_bar_edge top
tab_bar_style powerline
tab_title_template "{tab.active_wd.rsplit('/', 1)[-1]}"

kitty_mod cmd+option

map ctrl+cmd+option+u goto_layout tall
map ctrl+cmd+option+i goto_layout fat
map ctrl+cmd+option+o goto_layout stack

map ctrl+cmd+, load_config_file

map cmd+n new_window
map ctrl+shift+l next_window
map ctrl+shift+h previous_window


map ctrl+cmd+h swap_with_window

map ctrl+cmd+option+h resize_window narrower
map ctrl+cmd+option+l resize_window wider
map ctrl+cmd+option+k resize_window taller
map ctrl+cmd+option+j resize_window shorter 3

map kitty_mod+w close_window

map kitty_mod+a>d launch --type=background kitten quick-access-terminal
map kitty_mod+a>t launch --type=background kitten quick-access-terminal --config ~/github/dotfiles-latest/kitty/quick-access-terminal-center.conf --instance-group system-task /bin/bash -c '$HOME/github/dotfiles-latest/scripts/macos/mac/misc/240-systemTask.sh'
map kitty_mod+a>c launch --type=background kitten quick-access-terminal --config ~/github/dotfiles-latest/kitty/quick-access-terminal-center.conf --instance-group colorscheme-selector /bin/bash -c '$HOME/github/dotfiles-latest/colorscheme/colorscheme-selector.sh'
map kitty_mod+a>n launch --type=background kitten quick-access-terminal --config ~/github/dotfiles-latest/kitty/quick-access-terminal-daily.conf --instance-group daily-note /bin/bash -c '$HOME/github/dotfiles-latest/scripts/macos/mac/misc/301-dailyNote-float.sh'
map kitty_mod+a>s launch --type=background kitten quick-access-terminal --config ~/github/dotfiles-latest/kitty/quick-access-terminal-daily.conf --instance-group skitty-notes /bin/zsh -i -c 'export NEOVIM_MODE=skitty; export NVIM_APPNAME=neobean; cd "$HOME/github/skitty"; nvim ~/github/skitty/video-ideas.md'

map kitty_mod+i launch --stdin-source=@screen_scrollback --type=overlay /bin/zsh -c "NVIM_APPNAME=neobean SIMPLER_SCROLLBACK=deeznuts nvim +$ +'nnoremap q ZQ'"

background_tint 0.94
background_tint_gaps 0.97

background_tint 0.96
background_tint_gaps 0.98

background_tint 0.97
background_tint_gaps 0.99

background_tint 0.98
background_tint_gaps 0.99

background_opacity 1.0

background_opacity 1.0

# ----- Kitty tab shortcuts -----




startup_mode fullscreen

macos_traditional_fullscreen no
startup_session ~/.config/kitty/session.conf
