include ./base.conf

kitty_mod ctrl+shift+alt

map ctrl+shift+alt+u goto_layout tall
map ctrl+shift+alt+f goto_layout fat
map ctrl+shift+alt+o goto_layout stack

map ctrl+shift+f11 load_config_file

map ctrl+shift+n new_window
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+l next_window
map ctrl+shift+h previous_window

map ctrl+shift+alt+h swap_with_window

map kitty_mod+shift+h resize_window narrower
map kitty_mod+shift+l resize_window wider
map kitty_mod+shift+k resize_window taller
map kitty_mod+shift+j resize_window shorter 3

map kitty_mod+w close_window

map kitty_mod+i launch --stdin-source=@screen_scrollback --type=overlay /bin/zsh -c "nvim +$ +'nnoremap q ZQ'"

startup_mode maximized
