foreground              #f8f8f0
background              #000000
selection_foreground    #ffffff
selection_background    #264dff

cursor                  #ffffff
cursor_text_color       #000000

url_color               #40c4ff

active_border_color     #ff3366
inactive_border_color   #1e1e1e
bell_border_color       #ff5252

wayland_titlebar_color  #000000
macos_titlebar_color    #000000

active_tab_foreground   #ffffff
active_tab_background   #000000
inactive_tab_foreground #b3b3b3
inactive_tab_background #000000
tab_bar_background      #000000

mark1_foreground #000000
mark1_background #47ffa0
mark2_foreground #000000
mark2_background #40c4ff
mark3_foreground #000000
mark3_background #ff3366

color0  #000000
color8  #5c5c5c

color1  #f73232
color9  #ff5252

color2  #1afc65
color10 #47ffa0

color3  #fede5d
color11 #ffab40

color4  #36f9f6
color12 #40c4ff

color5  #ff7edb
color13 #e040fb

color6  #72f1b8
color14 #2ee2fa

color7  #f8f8f0
color15 #ffffff
